parameters:
#    shaduli_user.example.class: Shaduli\UserBundle\Example

services:
#    shaduli_user.example:
#        class: %shaduli_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
