services:
  sonata.admin.category:
    class: Shaduli\JobeetBundle\Admin\CategoryAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Quick Links", label: "Categories" }
    arguments: [ null, Shaduli\JobeetBundle\Entity\Category, SonataAdminBundle:CRUD ]
    calls:
      - [ setTranslationDomain, [ ShaduliJobeetBundle ] ]
  sonata.admin.job:
    class: Shaduli\JobeetBundle\Admin\JobAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Quick Links", label: "Jobs" }
    arguments: [ null, Shaduli\JobeetBundle\Entity\Job, SonataAdminBundle:CRUD ]
    calls:
      - [ setTranslationDomain, [ ShaduliJobeetBundle ] ]
  sonata.admin.user:
    class: Shaduli\JobeetBundle\Admin\UserAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Quick Links", label: Admins }
    arguments: [null, Shaduli\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        
         

