shaduli_jobeet_homepage:
    pattern:  /
    defaults: { _controller: "ShaduliJobeetBundle:Job:index" }

shaduli_jobeet_job_show_user:
    pattern:  /job/{id}/{company}/{location}/{position}
    defaults: { _controller: "ShaduliJobeetBundle:Job:show", company: null, location: null, position: null }
    requirements:
      id: \d+
      _method: GET
shaduli_jobeet_job_category:
    pattern:  /category/{slug}
    defaults: { _controller: "ShaduliJobeetBundle:Category:show" }
    requirements:
      _method: GET

shaduli_jobeet_job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ShaduliJobeetBundle:Job:edit" }
    requirements:
      { id: \d+ }

shaduli_jobeet_job_new:
    pattern:  /job/new
    defaults: { _controller: "ShaduliJobeetBundle:Job:new" }
    
shaduli_jobeet_job_create:
    pattern:  /create
    defaults: { _controller: "ShaduliJobeetBundle:Job:create" }
    requirements: { _method: post }
    
shaduli_jobeet_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "ShaduliJobeetBundle:Job:update" }
    requirements: { _method: post }

shaduli_jobeet_job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ShaduliJobeetBundle:Job:delete" }
    requirements: { _method: post }
